import { useState } from 'react';
import { ChevronDown, ImageUp } from 'lucide-react';
import { extractionApi } from '../../api';
import type { Confidence, ExtractionResult, ExtractionTemplate } from '../../types/api';
import { Badge, Busy, Button, Input, Select } from '../ui';

const confidenceLabels: Record<Confidence, string> = { high: 'Alta', medium: 'Media', low: 'Bassa' };
const confidenceTones: Record<Confidence, 'success' | 'warning' | 'danger'> = { high: 'success', medium: 'warning', low: 'danger' };
// Formati che il browser accetta di caricare. Il PDF e i multipagina non
// passano dal canvas: il ridimensionamento qui sotto serve a non spedire 12 MB
// di foto, ma un PDF di bolla è già leggero e va mandato intatto — è il server
// che lo rasterizza pagina per pagina.
export const EXTRACTION_FILE_ACCEPT = 'image/*,.heic,.heif,.pdf,application/pdf';

export async function prepareExtractionImage(file: File): Promise<File> {
  if (file.size > 15 * 1024 * 1024) throw new Error(`${file.name} supera il limite di 15 MB.`);
  if (file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf')) return file;
  let bitmap: ImageBitmap;
  try { bitmap = await createImageBitmap(file); } catch { throw new Error(file.name.toLowerCase().match(/\.hei[cf]$/) ? 'Il browser non supporta questo file HEIC. Nelle impostazioni della fotocamera scegli “Più compatibile” (JPEG) e riprova.' : `Impossibile leggere ${file.name}.`); }
  const scale = Math.min(1, 2000 / Math.max(bitmap.width, bitmap.height)); const width = Math.max(1, Math.round(bitmap.width * scale)); const height = Math.max(1, Math.round(bitmap.height * scale)); const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; const context = canvas.getContext('2d'); if (!context) throw new Error('Elaborazione immagine non disponibile.'); context.drawImage(bitmap, 0, 0, width, height); bitmap.close(); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error('Conversione JPEG non riuscita.')), 'image/jpeg', 0.88)); return new File([blob], file.name.replace(/\.[^.]+$/, '') + '.jpg', { type: 'image/jpeg', lastModified: file.lastModified });
}
export function PhotoExtract({ templates, onApply, onExtract }: { templates: ExtractionTemplate[]; onApply: (values: Record<string, string>) => void; onExtract?: (result: ExtractionResult) => void }) {
  const [templateId, setTemplateId] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<ExtractionResult | null>(null); const [values, setValues] = useState<Record<string, string>>({});
  const process = async (files: FileList | null) => { if (!files?.length) return; if (files.length > 5) { setError('Puoi inviare al massimo 5 immagini per volta.'); return; } setLoading(true); setError(''); try { const converted = await Promise.all(Array.from(files).map(prepareExtractionImage)); const extraction = await extractionApi.extract(converted, templateId || undefined); setResult(extraction); setValues(Object.fromEntries(Object.entries(extraction.fields).map(([target, field]) => [target, field.value]))); onExtract?.(extraction); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Analisi non riuscita. Riprova o compila i campi a mano.'); } finally { setLoading(false); } };
  return <section className="space-y-4 rounded-xl border bg-white p-4"><div><h3 className="font-semibold">Estrai dati da una foto</h3><p className="text-sm text-slate-600">I valori vengono solo proposti: controllali e applicali esplicitamente al form.</p></div><Select label="Tipo di oggetto" value={templateId} onChange={(event) => setTemplateId(event.target.value)}><option value="">Auto-rileva</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</Select><label className="flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-slate-300 p-4 text-center hover:bg-slate-50"><ImageUp/><span className="mt-2 font-medium">Scatta o scegli fino a 5 foto</span><input className="sr-only" type="file" accept={EXTRACTION_FILE_ACCEPT} capture="environment" multiple disabled={loading} onChange={(event) => void process(event.target.files)}/></label>{loading && <Busy title="Analisi dell'immagine in corso…">Di norma bastano pochi secondi. Non ricaricare la pagina.</Busy>}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{result && <div className="space-y-4"><p className="text-sm">Template usato: <strong>{result.template_name ?? 'automatico'}</strong> · Motore: {result.engine}</p>{Object.entries(result.fields).map(([target, field]) => <div key={target} className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input label={field.field.replaceAll('_', ' ')} value={values[target] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [target]: event.target.value }))}/><div className="self-end pb-2"><Badge tone={confidenceTones[field.confidence]}>Confidenza {confidenceLabels[field.confidence]}</Badge>{field.corrected && <Badge tone="warning">Corretto OCR</Badge>}</div></div>)}{Object.entries(result.conflicts).map(([target, candidates]) => <fieldset key={target} className="rounded-lg border border-amber-300 bg-amber-50 p-3"><legend className="font-semibold">Conflitto per {target}</legend>{candidates.map((candidate) => <label key={`${candidate.source}-${candidate.value}`} className="mt-2 flex gap-2"><input type="radio" name={target} value={candidate.value} checked={values[target] === candidate.value} onChange={() => setValues((current) => ({ ...current, [target]: candidate.value }))}/><span>{candidate.value} ({candidate.source})</span></label>)}</fieldset>)}<details className="rounded-lg border p-3"><summary className="flex cursor-pointer items-center gap-2 font-medium"><ChevronDown size={18}/>Cosa ha letto</summary><div className="mt-3 space-y-2 text-sm"><p><strong>Barcode:</strong> {result.raw_barcodes.join(', ') || 'Nessuno'}</p><pre className="max-h-48 overflow-auto whitespace-pre-wrap rounded bg-slate-100 p-3">{result.raw_ocr_text || 'Nessun testo OCR disponibile.'}</pre></div></details><Button type="button" onClick={() => onApply(values)}>Applica al form</Button></div>}</section>;
}
